# Generated by Django 3.2.9 on 2021-11-22 01:46

from django.db import migrations, models
import preprocessing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colname', models.CharField(max_length=200)),
                ('datatype', models.CharField(max_length=200)),
                ('contValues', models.TextField(blank=True)),
                ('catValues', models.TextField(blank=True)),
                ('changeable', models.BooleanField(default=False)),
                ('navalue', models.IntegerField(default=0)),
                ('nahandling', models.TextField(default='None')),
                ('target', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='metadataForReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colname', models.CharField(max_length=200)),
                ('datatype', models.CharField(max_length=200)),
                ('contValues', models.TextField(blank=True)),
                ('catValues', models.TextField(blank=True)),
                ('changeable', models.BooleanField(default=False)),
                ('navalue', models.IntegerField(default=0)),
                ('nahandling', models.TextField(default='None')),
                ('target', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Rawfile',
            fields=[
                ('file_name', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=preprocessing.models.upload_location)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawfileForReset',
            fields=[
                ('file_name', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='csvfileBackup')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
