# Generated by Django 3.2.9 on 2021-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataforreset',
            name='nahandling',
            field=models.TextField(default='No Action'),
        ),
    ]
