# Generated by Django 3.2.9 on 2021-11-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_alter_metadataforreset_nahandling'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelType', models.CharField(max_length=100)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='RawfileForReset',
        ),
    ]
