# Generated by Django 3.2.9 on 2021-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0003_auto_20211124_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfile',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawfile',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
