# Generated by Django 3.2.9 on 2021-12-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0004_auto_20211129_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
